SUBMISSION 1: How many rows are missing a value in the “State” column? Explain how you came up with the number.

5377 rows were state information is missing. 
Looking at the facets for state we sorted by count and then realize that there were 5377 blanks

SUBMISSION 2: How many rows with missing ZIP codes do you have?

4362 blanks indicating that theere are 4362 rows were the zipcodes are missing

SUBMISSION 3: If you consider all ZIP codes less than 99999 valid ZIP codes, how many valid and invalid ZIP codes do you have, respectively?

Created a new column named ValidZipCode and obtain the following results:
Valid Zip Codes = 345175
Invalid Zip Codes = 39323


SUBMISSION 5: Change the radius to 3.0. What happens? Do you want to merge any of the resulting matches?

Yes we want to merge results related to Alaska and California. However, we should not merge results related to Pakistan and Indonesia

SUBMISSION 6: Change the block size to 2. Give two examples of new clusters that may be worthwhile merging.

Merged Alaska, California and Canada

SUBMISSION 7: Explain in words what happens when you cluster the “place” column, and why you think that happened. What additional functionality could OpenRefine provide to possibly deal with the situation?

Clustering by place takes a long time because each place contains a lot of information which makes it difficul to compare with others. In this case is better to split the data into elements that can be more comparable. That's exactly what we did by extracting the state or country of the place in the location column

SUBMISSION 8: Submit a representation of the resulting matrix from the Leveshtein edit distance calculation. The resulting value should be correct.

In [25]:
import numpy as np

h_word = ["g","u","m","b","a","r","r","e","l"]
v_word = ["g","u","n","b","a","r","r","e","l"]

def leveshtein(v_word, h_word):
    n_rows = len(v_word)+1
    m_columns = len(h_word)+1
    d = np.zeros((n_rows, m_columns))
    for m in range(m_columns):
        for n in range(n_rows):
            if m == 0: d[n,m]=n
            elif n == 0: d[n,m]=m
            elif v_word[n-1] == h_word[m-1]: 
                cost=0
                d[n,m] = min (d[n-1,m]+1, d[n,m-1]+1, d[n-1, m-1]+cost)
            else: 
                cost = 1
                d[n,m] = min (d[n-1,m]+1, d[n,m-1]+1, d[n-1, m-1]+cost)
    distance = d[n_rows-1,m_columns-1]
    print "Here's the resulting matrix:"
    print d
    print
    print "Leveshtein distance is the value at d[%1d,%1d] = %1d"%(n_rows-1, m_columns-1,distance )
                 
leveshtein(v_word, h_word)

                 
            
        

Here's the resulting matrix:
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.  6.  7.]
 [ 3.  2.  1.  1.  2.  3.  4.  5.  6.  7.]
 [ 4.  3.  2.  2.  1.  2.  3.  4.  5.  6.]
 [ 5.  4.  3.  3.  2.  1.  2.  3.  4.  5.]
 [ 6.  5.  4.  4.  3.  2.  1.  2.  3.  4.]
 [ 7.  6.  5.  5.  4.  3.  2.  1.  2.  3.]
 [ 8.  7.  6.  6.  5.  4.  3.  2.  1.  2.]
 [ 9.  8.  7.  7.  6.  5.  4.  3.  2.  1.]]

Leveshtein distance is the value at d[9,9] = 1
